### ISSUE TITLE
[Hyper] Issue tracker of hyper.sh provider

### ISSUE THREAD

**Issue by resouer** [virtual-kubelet/virtual-kubelet#26]
Jimmy and I are refactoring and testing https://github.com/hyperhq/hyper.sh-connector-k8s with virtual-kubelet recently, so we just create this issue to track this part of work.

We will update the tracker periodically, and also figure out which API can not be implemented for now.

- [x] CreatePod(pod *v1.Pod) error
- [x] UpdatePod(pod *v1.Pod) error
- [x] DeletePod(pod *v1.Pod) error
- [x] GetPod(namespace, name string) (*v1.Pod, error)
- [x] GetPodStatus(namespace, name string) (*v1.PodStatus, error)
- [x] GetPods() ([]*v1.Pod, error)
- [ ] Capacity() v1.ResourceList
- [ ] NodeConditions() []v1.NodeCondition
- [ ] OperatingSystem() string

**Comment by rbitia** [comment]
Hey! Are we good to close this issue?

**Comment by resouer** [comment]
@rbitia Yes, Ria! The rest of tasks are already in, I will close it!
